spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/musiclistener"
    username: postgres
    password: postgres

server:
  error:
    include-message: always

app:
  musicplayer:
    baseurl: http://localhost:8081

